### ISSUE TITLE
Contributing to OpenJDK

### ISSUE THREAD

**Issue by navidR** [JetBrains/jdk8u_jdk#1]
I noticed jetbrains have done such wonderful job in fixing font rendering in Linux (which was awful) and I personally really appreciate it.

But since Swing apps font rendering with OpenJDK/Oracle is miserable , 
1) Do you think it is possible to contribute your patch to upstream OpenJDK? 
2) Is it in your plan ? 
3) Or your only plan in fixing it for Jetbran/jdk only ? 
4) Will Oracle/OpenJDK engineers accept font rendering fix patch ?

So many people have problem with Java font rendering in Linux and your fix would be really improve java desktop apps overall quality in Free Software Community.

**Comment by avu** [comment]
Yes, we're going to submit our fix into OpenJDK but it will take some time to go through their internal review and testing.

**Comment by navidR** [comment]
Thank you , and I should thank jetbrain for such wonderful job , I am really grateful.
This can be closed in my opinion.
