### ISSUE TITLE
windows/native/sun/windows/awt.h uses wrong calling convention for EnableNonClientDpiScaling

### ISSUE THREAD

**Issue by mpll** [JetBrains/jdk8u_jdk#12]
EnableNonClientDpiScalingFunc is declared in awt.h as follows:

* typedef BOOL(EnableNonClientDpiScalingFunc)(HWND);

The correct declaration should be:

* typedef BOOL(WINAPI EnableNonClientDpiScalingFunc)(HWND);

Without the WINAPI qualifier, the code gets compiled assuming EnableNonClientDpiScaling is a cdecl function when it's actually stdcall. This corrupts the stack pointer when the function is called, causing a crash when running x86 version of IntelliJ on Windows.

Commit eae44018e2ca06b589f487b83bb84c857af697ad attempted to fix this by skipping the EnableNonClientDpiScaling call if running under WOW64. However, this code still crashes when running under x86 emulation on ARM64 Windows (and I imagine would also crash on native x86).

The right fix is to explicitly declare EnableNonClientDpiScalingFunc as WINAPI, and remove the IsWow64Process call, which is only masking the problem.

The AreDpiAwarenessContextsEqual declaration (that was removed by the above commit) had the same problem by the way.

**Comment by forantar** [comment]
Pavel,

Thank you for your finding! We will fix it.
