### ISSUE TITLE
IME Composition Window is displayed at incorrect location

### ISSUE THREAD

**Issue by slankka** [JetBrains/jdk8u_jdk#16]
## Hello, I found a problem with the latest IDEA IC 2018.1.1。

The problem is : 
I'm using Chinese IME called Mircosoft Pinyin，Windows 10 bundled.
When I typing, the IME Composition Window is displayed at incorrect location. 
The normal IME Composition window will follow the cursor, but it does not follow.
![abnormal](https://user-images.githubusercontent.com/8142133/38765973-bbe7a594-3ffd-11e8-88fc-4ce52b226fb9.jpg)

When I switch IDEA boot JDK to Oracle JDK 1.8_8u151，the problem is solved.
![normal](https://user-images.githubusercontent.com/8142133/38765979-c6f5371c-3ffd-11e8-8b91-c8d1afc93d2b.jpg)

My IDEA version:
```
IntelliJ IDEA 2018.1.1 (Community Edition)
Build #IC-181.4445.78, built on April 10, 2018
JRE: 1.8.0_152-release-1136-b27 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

winver:
```Windows 10 1709 (16299.371)```

I think these links may be helpful.
https://bugs.openjdk.java.net/browse/JDK-8147842
https://bugs.openjdk.java.net/browse/JDK-8178933
https://youtrack.jetbrains.com/issue/WI-32868#u=1471247366618

There is an easy way to reproduce the problem noticed in the first link:
```
package test; 

import javax.swing.JEditorPane; 
import javax.swing.JFrame; 

public class IMETest { 

public static void main(String[] args) { 
    JFrame myFrame = new JFrame("IME Test"); 
    myFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); 
    myFrame.setSize(300,200); 

    JEditorPane myPane = new JEditorPane(); 

    myFrame.setContentPane(myPane); 
    myFrame.setVisible(true); 
    }
}
```
Then using Mircosoft Pinyin IME，run it by JB JRE 1.8.0_152-release-1136-b27 amd64。

There are many duplicate issues related to this problem on jetbrains youtrack，some questions may be not clear.

Could you please fix the problem? Or the problem has been already fixed, but I don't know.

**Comment by vprovodin** [comment]
Dear slankka
This issue is being tracked by https://youtrack.jetbrains.com/issue/JRE-365. At this moment it has been fixed. The fix is being expected in the coming IDEA release 2018.2

Thank you

**Comment by slankka** [comment]
Thanks a lot，I received the update patch of release 2018.2 this mid night. The problem is gone.
