### ISSUE TITLE
Document branching strategy

### ISSUE THREAD

**Issue by raboof** [JetBrains/jdk8u_jdk#17]
Hi!

I've noticed a (admittedly obscure) problem with modal dialogs in IntelliJ IDEA (https://github.com/raboof/notion/issues/62) that exists when using this shipped OpenJDK but not when using debian/ubuntu's OpenJDK.

To provide a more useful bug report, however, I'd like to dig into the code a bit first. It's not quite clear to me how the different branches relate though, is that documented somewhere?

**Comment by shokre** [comment]
Problem is not just with modal dialogs, but with menus, navigation and code popups also.

**Comment by avu** [comment]
Thanks for reporting, here is the issue for tracking https://youtrack.jetbrains.com/issue/JRE-761

**Comment by raboof** [comment]
The problem with transient windows indeed seems to be gone in idea-IC-181.5087.6.

It'd still be useful to document the branching strategy, but indeed I don't need it anymore myself :).
