### ISSUE TITLE
Push release builds to Bintray

### ISSUE THREAD

**Issue by IceMan81** [JetBrains/jdk8u_jdk#2]
Could you guys please push out the release builds to bintray? The 64-bit equivalents of the 32bits builds available with the EAPs are not pushed to bintray.

Thanks

**Comment by bulenkov** [comment]
Will do, thanks.

**Comment by IceMan81** [comment]
@bulenkov Ok. I asked because the EAP released today has bundled the 32bit build 216 but as I use 64-bit Intellij I don't have the 64-bit build to use with EAP

**Comment by IceMan81** [comment]
@bulenkov If the newer builds that are tagged as releases are made available on bintray we EAP users could test it out for you.

**Comment by IceMan81** [comment]
@bulenkov any chance one of the newer builds will be released to bintray?

**Comment by bulenkov** [comment]
Hello, we release every verified release to bintray. Take a look under versions. The latest should be around #408 The pinned version is what we use in latest major releases in our products

**Comment by IceMan81** [comment]
@bulenkov I agree, most times things released to bintray, but sometimes there are differences; Like right now, the 64-bit Windows build did not get updated, while every other build was updated to b494.
