### ISSUE TITLE
Vertically Oriented fonts disappear in Intellij when using jb8u112-b297

### ISSUE THREAD

**Issue by IceMan81** [JetBrains/jdk8u_jdk#3]
I tried the newly released released 8u112-b297 for 64-bit Windows. The only issue I noticed is that vertically oriented fonts don't display. See screenshots of the various tool windows in Intellij : Projects, Structure, Favorites etc.

![image](https://cloud.githubusercontent.com/assets/1093778/17978041/05d67008-6aa9-11e6-98a3-392f2e506dd1.png)
![image](https://cloud.githubusercontent.com/assets/1093778/17978043/10011f60-6aa9-11e6-965a-13a465ee102e.png)

**Comment by IceMan81** [comment]
FYI, this issue happens with the 8u112-b287 that was released and bundled with the new EAP that was released.

**Comment by bulenkov** [comment]
Are you still experiencing the issue with new builds? Can you write a simple java test demonstrating the issue? All paintings here are done by simple transformations (rotate). You can take a look here: https://upsource.jetbrains.com/idea-ce/file/idea-ce-a89e8304525717593ade52ac9a77ac686a70012e/platform/platform-impl/src/com/intellij/openapi/wm/impl/StripeButtonUI.java?nav=4640:5230:focused&line=182

**Comment by JB-Dmitry** [comment]
Do you have mactype or gdipp installed? If yes, workaround described in https://youtrack.jetbrains.com/issue/JRE-19 might help.

**Comment by IceMan81** [comment]
Yes, that helps. I had gdipp installed. With the latest MacType Intellij works quite well. JRE-19 was opening by me. Thanks for the comments.

**Comment by IceMan81** [comment]
This issue is resolved.
